version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: db_fakultas
      MYSQL_ROOT_PASSWORD: root  # pastikan sama dengan DB_PASSWORD di .env
    ports:
      - "13306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

